---

- name: set vim as default editor
  alternatives:
    name: editor
    link: '{{ console_editor_link }}'
    path: '{{ console_editor_path }}'

- name: configure bash
  template:
    src: etc/bashrc.j2
    dest: '{{ console_bashrc }}'
    owner: root
    group: root
    mode: 0644
    seuser: system_u
    serole: object_r
    setype: etc_t
    selevel: s0
  tags:
    - 'role::console'
    - 'role::console:config'

- name: configure vim
  template:
    src: etc/vimrc.j2
    dest: '{{ console_vimrc }}'
    owner: root
    group: root
    mode: 0644
    seuser: system_u
    serole: object_r
    setype: etc_t
    selevel: s0
  tags:
    - 'role::console'
    - 'role::console:config'

- name: configure git
  template:
    src: etc/gitconfig.j2
    dest: '{{ console_gitconfig }}'
    owner: root
    group: root
    mode: 0644
    seuser: system_u
    serole: object_r
    setype: etc_t
    selevel: s0
  tags:
    - 'role::console'
    - 'role::console:config'
